openapi: '3.1.0'
info:
  title: User Service API
  version: '1.0.0'
  description: User service to manage user profiles.
servers:
  - url: https://{gateway-host}/user
    description: Public access to the User Service via the Gateway
    variables:
      gateway-host:
        default: "localhost:8080"
        description: The host and port of the public-facing Spring Cloud Gateway
paths:
  /:
    get:
      operationId: getAllUsers
      summary: Get all users
      responses:
        '200':
          description: List of users retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserProfile'
        '500':
          description: Server error
  /{id}:
    get:
      operationId: getUserById
      summary: Get user profile
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '404':
          description: User not found
        '500':
          description: Server error
    put:
      operationId: updateUserById
      summary: Update user info
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdate'
      responses:
        '200':
          description: User info updated successfully
        '400':
          description: Invalid input
        '404':
          description: User not found
        '500':
          description: Server error
    delete:
      operationId: deleteUserById
      summary: Delete user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: User deleted successfully
        '404':
          description: User not found
        '500':
          description: Server error
  /register:
    post:
      operationId: addUser
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistration'
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Invalid input
        '500':
          description: Server error
  /password:
    post:
      operationId: getUserPassword
      summary: Fetch user hashed password â€“ internal API for Auth Services
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Email'
      responses:
        '200':
          description: Token is valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserLoginResponse'
        '401':
          description: Invalid token
        '500':
          description: Server error
  /password/{id}:
    patch:
      operationId: changePassword
      summary: Change password
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserPasswordRequest'
      responses:
        '200':
          description: Password changed successfully
        '400':
          description: Invalid input
        '404':
          description: User not found
        '500':
          description: Server error
  /email/{id}:
    patch:
      operationId: changeEmail
      summary: Change email
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserEmailRequest'
      responses:
        '200':
          description: Email changed successfully
        '400':
          description: Invalid input
        '404':
          description: User not found
        '500':
          description: Server error
  /role/{id}:
    patch:
      operationId: changeRole
      summary: Change role
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRoleRequest'
      responses:
        '200':
          description: Role changed successfully
        '400':
          description: Invalid input
        '404':
          description: User not found
        '500':
          description: Server error
components:
  schemas:
    UserUpdate:
      $ref: '../../../../ms-models/src/main/resources/common-api.yaml#/components/schemas/UserUpdate'
    UserRegistration:
      $ref: '../../../../ms-models/src/main/resources/common-api.yaml#/components/schemas/UserRegistration'
    Email:
      $ref: '../../../../ms-models/src/main/resources/common-api.yaml#/components/schemas/Email'
    UserLoginResponse:
      $ref: '../../../../ms-models/src/main/resources/common-api.yaml#/components/schemas/UserLoginResponse'
    UserPasswordRequest:
      $ref: '../../../../ms-models/src/main/resources/common-api.yaml#/components/schemas/UserPasswordRequest'
    UserEmailRequest:
      $ref: '../../../../ms-models/src/main/resources/common-api.yaml#/components/schemas/UserEmailRequest'
    UserRoleRequest:
      $ref: '../../../../ms-models/src/main/resources/common-api.yaml#/components/schemas/UserRoleRequest'
    UserProfile:
      $ref: '../../../../ms-models/src/main/resources/common-api.yaml#/components/schemas/UserProfile'