spring:
  application:
    name: Auth Service
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USER:myuser}
    password: ${DB_PASS:mypassword}
    driver-class-name: org.postgresql.Driver

server:
  port: 8088

jwt:
  expiration: 6000000
  secret: ${JWT_SECRET}

admin:
  username: admin@matrix.com
  password: bewrOoaRMzDByw7xz8WQYZYR43l5Gd/aAabyRLVkEyk=