openapi: '3.1.0'
info:
  title: Auth Service
  version: '1.0.0'
  description: Authenticate service to manage user profiles.
servers:
  - url: https://{gateway-host}/auth
    description: Public access to the Auth Service via the Gateway
    variables:
      gateway-host:
        default: "localhost:8080"
        description: The host and port of the public-facing Spring Cloud Gateway
paths:
  /login:
    post:
      tags:
        - Auth
      summary: Logs user into the system.
      description: Authenticate user and return JWT
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: successful authentication
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JwtTokenResponse'
        '401':
          description: Invalid credential
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MatrixError"
        '403':
          description: User disabled
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MatrixError"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MatrixError"
  /logout:
    post:
      tags:
        - Auth
      summary: Logs out current logged in user session.
      description: Invalidate current JWT token
      operationId: logoutUser
      security:
        - BearerAuth: []
      responses:
        '204':
          description: Successfully logged out
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MatrixError"
  /refresh:
    post:
      tags:
        - Auth
      summary: Refresh token â€“ new token without login again
      description: New JWT token issued
      operationId: refreshToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshTokenRequest'
      responses:
        '200':
          description: New JWT token issued
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JwtTokenResponse'
        '400':
          description: Invalid jwt token
        '401':
          description: Expired refresh jwt token
        '404':
          description: User not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MatrixError"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    LoginRequest:
      $ref: '../../../../ms-models/src/main/resources/common-api.yaml#/components/schemas/LoginRequest'
    JwtTokenResponse:
      $ref: '../../../../ms-models/src/main/resources/common-api.yaml#/components/schemas/JwtTokenResponse'
    MatrixError:
      $ref: '../../../../ms-models/src/main/resources/common-api.yaml#/components/schemas/MatrixError'
    RefreshTokenRequest:
      $ref: '../../../../ms-models/src/main/resources/common-api.yaml#/components/schemas/RefreshTokenRequest'

